services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: local
    volumes:
      - mysqldata:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 520M
          cpus: '0.25'
        reservations:
          memory: 260M
          cpus: '0.20'
volumes:
  mysqldata:
